Repository SuryaFtr/group-n-project, pull requests merged in 2023-12, with the labels that each got.

#45 feat: #44 Add feature get program by id
  backend/controllers/programController.js
  backend/routes/program.js
Labels: enhancement

#47 feat: #46 Add feature update program
  backend/controllers/programController.js
  backend/routes/program.js
Labels: enhancement

#49 feat: #48 Add feature delete program
  backend/controllers/programController.js
  backend/routes/program.js
Labels: enhancement

#52 fix: #51 fix bug jwt, rbac & user routes
  backend/models/Auth.js
  backend/models/permissions_utils.js
  backend/routes/user.js
Labels: bug

#55 feat: #38 news endpoint feature
  backend/controllers/newsController.js
  backend/index.js
  backend/models/News.js
  backend/models/User.js
  backend/routes/news.js
Labels: enhancement

#58 #57 Rombak Main Page & Enhancement
  frontend/src/assets/Oceanss.jpg
  frontend/src/assets/Vector.png
  frontend/src/assets/Vector1.png
  frontend/src/components/Main/index.js
  frontend/src/components/Register/index.js
  frontend/src/styles/App.css
  frontend/src/styles/Main.css
Labels: enhancement

#62 feat: #61 Add feature get all event
  backend/controllers/eventController.js
  backend/routes/event.js
Labels: enhancement

#64 feat: #63 Add feature get event by id
  backend/controllers/eventController.js
  backend/routes/event.js
Labels: enhancement

#66 feat: #65 Add feature update event
  backend/controllers/eventController.js
  backend/routes/event.js
Labels: enhancement

#68 feat: #67 Add feature delete event
  backend/controllers/eventController.js
  backend/routes/event.js
Labels: enhancement

#75 56 admin panel
  backend/index.js
  backend/middleware/index.js
  backend/middleware/multer.js
  backend/middleware/validator.js
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/AdminPanel/datatable/TablePrograms.jsx
  frontend/src/pagesAdminPanel/new/New.scss
  frontend/src/pagesAdminPanel/new/NewProgram.jsx
  frontend/src/pagesAdminPanel/single/DetailProgram.jsx
  frontend/src/pagesAdminPanel/single/Single.scss
Labels: bug, enhancement

#81 fix: api url, whitelist frontend origin
  backend/index.js
  frontend/src/components/function/index.js
Labels: bug

#83 fix: bugs mongodb connection
  backend/index.js
Labels: bug

#85 84 add content on main page
  backend/routes/news.js
  frontend/src/App.js
  frontend/src/components/AdminPanel/datatable/TableNews.jsx
  frontend/src/components/Events/index.js
  frontend/src/components/News/index.js
  frontend/src/components/function/index.js
  frontend/src/fetch/dataTableApi.js
  frontend/src/pagesAdminPanel/index.js
  frontend/src/pagesAdminPanel/list/ListNews.jsx
  frontend/src/pagesAdminPanel/new/NewNews.jsx
  frontend/src/styles/Events.css
Labels: bug, enhancement
